package ccms_mvc.view.Civilian;

import ccms_mvc.controller.Civilian.CivilianSearchCntl;
import ccms_mvc.model.CourtCases;
import ccms_mvc.model.Person;
import java.util.ArrayList;

/**
 *
 * @author Tiffany Dove
 */
public class CivilianSearchUI extends javax.swing.JFrame {

    //Reference to Person Controller
    private CivilianSearchCntl civilianSearchCntl;
    //An arrayList of Person
    private ArrayList<Person> arrayListPerson;
    //An arrayList of Person
    private ArrayList<CourtCases> arrayListCourtCases;
    //Counter of the current Person
    private int indexOfCurrentPerson = 0;
    //Reference to Person class
    private Person person;

    public int getIndexOfCurrentPerson() {
        return indexOfCurrentPerson;
    }

    /**
     * Creates new form PersonUI
     */
    public CivilianSearchUI(CivilianSearchCntl civilianSearchCntl) {
        this.civilianSearchCntl = civilianSearchCntl;
        initComponents();
//        arrayListPerson = civilianSearchCntl.getListOfPerson();
//        arrayListCourtCases = civilianSearchCntl.getListOfCourtCases();
        //Get a Person occurrence from the arrayList using the current position.
        //namely current person.
        person = arrayListPerson.get(indexOfCurrentPerson);
        //Using the Person (person) class, take the values and populate
        //the UI.

//        parsePerson(person);
    }

//    public void parsePerson(Person person) {
//        //set the UI's id num text field with the id num from Person
//        idNumTextField.setText(String.valueOf(person.getIdNum()));
//        //set the UI's name text field with the name from Person
//        nameTextField.setText(person.getName());
//        //set the UI's address text field with the address from Person
//        addressTextField.setText(person.getAddress());
//        //set the UI's city text field with the city from Person
//        cityTextField.setText(person.getCity());
//        //set the UI's state text field with the state from Person
//        stateTextField.setText(person.getState());
//        //set the UI's zip code text field with the zip code from Person
//        zipCodeTextField.setText(String.valueOf(person.getZipCode()));
//    }
    public void clearTheFieldsInPersonUI() {
        //set the UI's id num text field with the id num from Person
        caseNumberTextField.setText("");
    }

    public String getCaseNumberTextField() {
        return caseNumberTextField.getText();
    }

    public void setCaseNumberTextField(String caseNumberTextFieldString) {
        this.caseNumberTextField.setText(caseNumberTextFieldString);
    }

    public void enableButtons(boolean enabled) {
        this.btnCivilianMainMenu.setEnabled(enabled);
        this.btnSearch.setEnabled(enabled);
        this.btnQuit.setEnabled(enabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        civilianSearchSpecificCasesPanel = new javax.swing.JPanel();
        ccmsLabel = new javax.swing.JLabel();
        caseNumberLabel = new javax.swing.JLabel();
        caseNumberTextField = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnCivilianMainMenu = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        civilianSearchSpecificCasesLabel = new javax.swing.JLabel();
        errorMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        civilianSearchSpecificCasesPanel.setToolTipText("Civilian - Search Specific Cases Panel");

        ccmsLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ccmsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ccmsLabel.setText("Court Case Managment System");
        ccmsLabel.setToolTipText("Court Case Management System");

        caseNumberLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        caseNumberLabel.setText("Case Number:");
        caseNumberLabel.setToolTipText("Case Number:");

        caseNumberTextField.setToolTipText("Please Enter Valid Case Number (i.e. 11111)");
        caseNumberTextField.setName("caseNumberTextField"); // NOI18N

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setToolTipText("Civilian Search Specific Cases");

        btnCivilianMainMenu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnCivilianMainMenu.setText("Civilian Main Menu");
        btnCivilianMainMenu.setToolTipText("Return to Civilian Main Menu");

        btnQuit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnQuit.setText("Quit");
        btnQuit.setToolTipText("Exit the Application");

        civilianSearchSpecificCasesLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        civilianSearchSpecificCasesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        civilianSearchSpecificCasesLabel.setText("Civilian - Search Specific Cases");
        civilianSearchSpecificCasesLabel.setToolTipText("Civilian - Search Specific Cases");

        errorMessage.setForeground(new java.awt.Color(255, 0, 0));
        errorMessage.setToolTipText("");

        javax.swing.GroupLayout civilianSearchSpecificCasesPanelLayout = new javax.swing.GroupLayout(civilianSearchSpecificCasesPanel);
        civilianSearchSpecificCasesPanel.setLayout(civilianSearchSpecificCasesPanelLayout);
        civilianSearchSpecificCasesPanelLayout.setHorizontalGroup(
            civilianSearchSpecificCasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(civilianSearchSpecificCasesPanelLayout.createSequentialGroup()
                .addGroup(civilianSearchSpecificCasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(civilianSearchSpecificCasesPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(civilianSearchSpecificCasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ccmsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(civilianSearchSpecificCasesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, civilianSearchSpecificCasesPanelLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(civilianSearchSpecificCasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(civilianSearchSpecificCasesPanelLayout.createSequentialGroup()
                                .addComponent(btnSearch)
                                .addGap(85, 85, 85)
                                .addComponent(btnCivilianMainMenu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnQuit))
                            .addGroup(civilianSearchSpecificCasesPanelLayout.createSequentialGroup()
                                .addGroup(civilianSearchSpecificCasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(civilianSearchSpecificCasesPanelLayout.createSequentialGroup()
                                        .addComponent(caseNumberLabel)
                                        .addGap(54, 54, 54)
                                        .addComponent(caseNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(errorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 83, Short.MAX_VALUE)))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        civilianSearchSpecificCasesPanelLayout.setVerticalGroup(
            civilianSearchSpecificCasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(civilianSearchSpecificCasesPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ccmsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(civilianSearchSpecificCasesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(civilianSearchSpecificCasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(caseNumberLabel)
                    .addComponent(caseNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(errorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addGroup(civilianSearchSpecificCasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, civilianSearchSpecificCasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSearch)
                        .addComponent(btnCivilianMainMenu))
                    .addComponent(btnQuit, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(civilianSearchSpecificCasesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(civilianSearchSpecificCasesPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCivilianMainMenu;
    public javax.swing.JButton btnQuit;
    public javax.swing.JButton btnSearch;
    private javax.swing.JLabel caseNumberLabel;
    private javax.swing.JTextField caseNumberTextField;
    private javax.swing.JLabel ccmsLabel;
    private javax.swing.JLabel civilianSearchSpecificCasesLabel;
    private javax.swing.JPanel civilianSearchSpecificCasesPanel;
    public javax.swing.JLabel errorMessage;
    // End of variables declaration//GEN-END:variables

}
