package ccms_mvc.view;

import ccms_mvc.controller.LoginIdCntl;
import ccms_mvc.model.Person;
import java.util.ArrayList;

/**
 *
 * @author Tiffany Dove
 */
public class LawyerUI extends javax.swing.JFrame {

//    //Reference to Person Controller
//    private LoginIdCntl personCntl;
//    //An arrayList of Person
//    private ArrayList<Person> arrayListPerson;  
//    //Counter of the current Person
//    private int indexOfCurrentPerson = 0;
//    //Reference to Person class
//    private Person person;
//
//    public int getIndexOfCurrentPerson() {
//        return indexOfCurrentPerson;
//    }
//
//    public void setIndexOfCurrentPerson(int indexOfCurrentPerson) {
//        this.indexOfCurrentPerson = indexOfCurrentPerson;
//    }
//            
//    /**
//     * Creates new form PersonUI
//     */
//    public LawyerUI(LoginIdCntl personCntl) {
//        this.personCntl = personCntl;
//        initComponents();
//        arrayListPerson = personCntl.getListOfCourtCases();
//        //Get a Person occurrence from the arrayList using the current position.
//        //namely current person.
//        person = arrayListPerson.get(indexOfCurrentPerson);
//        //Using the Person (person) class, take the values and populate
//        //the UI.
//        parsePerson(person);
//    }
//
//    public void parsePerson(Person person) {
//        //set the UI's id num text field with the id num from Person
//        idNumTextField.setText(String.valueOf(person.getIdNum()));
//        //set the UI's name text field with the name from Person
//        nameTextField.setText(person.getName());
//        //set the UI's address text field with the address from Person
//        addressTextField.setText(person.getAddress());
//        //set the UI's city text field with the city from Person
//        cityTextField.setText(person.getCity());
//        //set the UI's state text field with the state from Person
//        stateTextField.setText(person.getState());
//        //set the UI's zip code text field with the zip code from Person
//        zipCodeTextField.setText(String.valueOf(person.getZipCode()));
//    }
//
//    public void clearTheFieldsInPersonUI() {
//        //set the UI's id num text field with the id num from Person
//        idNumTextField.setText("");
//        //set the UI's name text field with the name from Person
//        nameTextField.setText("");
//        //set the UI's address text field with the address from Person
//        addressTextField.setText("");
//        //set the UI's city text field with the city from Person
//        cityTextField.setText("");
//        //set the UI's state text field with the state from Person
//        stateTextField.setText("");
//        //set the UI's zip code text field with the zip code from Person
//        zipCodeTextField.setText("");
//    }
//
//    public String getAddressTextField() {
//        return addressTextField.getText();
//    }
//
//    public void setAddressTextField(String addressTextFieldString) {
//        this.addressTextField.setText(addressTextFieldString);
//    }
//
//    public String getCityTextField() {
//        return cityTextField.getText();
//    }
//
//    public void setCityTextField(String cityTextFieldString) {
//        this.cityTextField.setText(cityTextFieldString);
//    }
//
//    public String getIdNumTextField() {
//        return idNumTextField.getText();
//    }
//
//    public void setIdNumTextField(String idNumTextFieldString) {
//        this.idNumTextField.setText(idNumTextFieldString);
//    }
//
//    public String getNameTextField() {
//        return nameTextField.getText();
//    }
//
//    public void setNameTextField(String nameTextFieldString) {
//        this.nameTextField.setText(nameTextFieldString);
//    }
//
//    public String getStateTextField() {
//        return stateTextField.getText();
//    }
//
//    public void setStateTextField(String stateTextFieldString) {
//        this.stateTextField.setText(stateTextFieldString);
//    }
//
//    public String getZipCodeTextField() {
//        return zipCodeTextField.getText();
//    }
//
//    public void setZipCodeTextField(String zipCodeTextFieldString) {
//        this.zipCodeTextField.setText(zipCodeTextFieldString);
//    }
//    
//    public void enableButtons(boolean enabled){
//        this.btnAdd.setEnabled(enabled);
//        this.btnDelete.setEnabled(enabled);
//        this.btnNext.setEnabled(enabled);
//        this.btnPrevious.setEnabled(enabled);
////        this.btnQuit.setEnabled(enabled);
//        this.btnUpdate.setEnabled(enabled);
//        this.btnSave.setEnabled(!enabled);
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personPanel = new javax.swing.JPanel();
        personLabel = new javax.swing.JLabel();
        idNumLabel = new javax.swing.JLabel();
        idNumTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cityTextField = new javax.swing.JTextField();
        stateLabel = new javax.swing.JLabel();
        stateTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        zipCodeTextField = new javax.swing.JTextField();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        personPanel.setToolTipText("Person Panel");

        personLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        personLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        personLabel.setText("PERSON");
        personLabel.setToolTipText("");

        idNumLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        idNumLabel.setText("ID Num:");

        idNumTextField.setToolTipText("Please enter ID num.");
        idNumTextField.setName("idNumTextField"); // NOI18N

        nameTextField.setToolTipText("Please enter name.");

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        nameLabel.setText("Name:");

        addressLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        addressLabel.setText("Address:");

        addressTextField.setToolTipText("Please enter address.");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("City:");

        cityTextField.setToolTipText("Please enter city.");
        cityTextField.setMinimumSize(new java.awt.Dimension(100, 100));

        stateLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        stateLabel.setText("State:");

        stateTextField.setToolTipText("Please enter state.");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Zip Code:");

        zipCodeTextField.setToolTipText("Please enter zip code. ");

        btnPrevious.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnPrevious.setText("Previous");
        btnPrevious.setToolTipText("to move backwards");

        btnNext.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnNext.setText("Next");
        btnNext.setToolTipText("to move fowards through the objects in teh ArrayList");

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setToolTipText("Add a new object to the list");

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setToolTipText("Make changes to an existing object");

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setToolTipText("remove the current object");

        btnQuit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnQuit.setText("Quit");
        btnQuit.setToolTipText("exit the application");

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSave.setText("Save");
        btnSave.setEnabled(false);

        javax.swing.GroupLayout personPanelLayout = new javax.swing.GroupLayout(personPanel);
        personPanel.setLayout(personPanelLayout);
        personPanelLayout.setHorizontalGroup(
            personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personPanelLayout.createSequentialGroup()
                        .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idNumLabel)
                            .addComponent(nameLabel)
                            .addComponent(addressLabel)
                            .addComponent(jLabel1)
                            .addComponent(stateLabel)
                            .addComponent(jLabel2))
                        .addGap(54, 54, 54)
                        .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(cityTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zipCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(personPanelLayout.createSequentialGroup()
                        .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdd)
                            .addComponent(btnPrevious))
                        .addGap(25, 25, Short.MAX_VALUE)
                        .addComponent(btnUpdate)
                        .addGap(50, 50, 50)
                        .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personPanelLayout.createSequentialGroup()
                                .addComponent(btnDelete)
                                .addGap(56, 56, 56)
                                .addComponent(btnQuit))
                            .addComponent(btnNext))))
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(personLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
            .addGroup(personPanelLayout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        personPanelLayout.setVerticalGroup(
            personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(personLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(zipCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(personPanelLayout.createSequentialGroup()
                        .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idNumLabel)
                            .addComponent(idNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressLabel)
                            .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(34, 34, 34)
                        .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stateLabel)
                            .addComponent(stateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addGap(31, 31, 31)
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPrevious, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNext, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnQuit, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(26, 26, 26)
                .addComponent(btnSave)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(personPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 228, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(personPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextField;
    public javax.swing.JButton btnAdd;
    public javax.swing.JButton btnDelete;
    public javax.swing.JButton btnNext;
    public javax.swing.JButton btnPrevious;
    public javax.swing.JButton btnQuit;
    public javax.swing.JButton btnSave;
    public javax.swing.JButton btnUpdate;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JLabel idNumLabel;
    private javax.swing.JTextField idNumTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel personLabel;
    private javax.swing.JPanel personPanel;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTextField stateTextField;
    private javax.swing.JTextField zipCodeTextField;
    // End of variables declaration//GEN-END:variables

}
