package ccms_mvc.view;

import ccms_mvc.controller.MainMenuCntl;

/**
 *
 * @author Tiffany Dove
 */
public class MainMenuUI extends javax.swing.JFrame {

    //Reference to Main Menu Controller
    private MainMenuCntl mainMenuCntl;
            
    /**
     * Creates new form MainMenuUI
     */
    public MainMenuUI(MainMenuCntl mainMenuCntl) {
        this.mainMenuCntl = mainMenuCntl;
        initComponents();
    }

    public void setErrorMessageString(String errorMessageString) {
        this.errorMessageLabel.setText(errorMessageString);
    }

    public void enableButtons(boolean enabled){
        
        this.btnCivilianMainMenu.setEnabled(enabled);
        this.btnClerkMainMenu.setEnabled(enabled);
        this.bntJudgeMainMenu.setEnabled(enabled);
        this.btnLawyerMainMenu.setEnabled(enabled);
        this.btnQuit.setEnabled(enabled);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ccmsMainMenuPanel = new javax.swing.JPanel();
        ccmsMainMenuLabel = new javax.swing.JLabel();
        btnQuit = new javax.swing.JButton();
        bntJudgeMainMenu = new javax.swing.JButton();
        btnCivilianMainMenu = new javax.swing.JButton();
        btnClerkMainMenu = new javax.swing.JButton();
        btnLawyerMainMenu = new javax.swing.JButton();
        errorMessageLabel = new javax.swing.JLabel();
        mainMenuLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ccmsMainMenuPanel.setToolTipText("Main menu Panel");

        ccmsMainMenuLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ccmsMainMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ccmsMainMenuLabel.setText("Court Case Management System");
        ccmsMainMenuLabel.setToolTipText("Court Case Management System");

        btnQuit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnQuit.setText("Quit");
        btnQuit.setToolTipText("exit the application");

        bntJudgeMainMenu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bntJudgeMainMenu.setText("Judge Main Menu");
        bntJudgeMainMenu.setToolTipText("Judge Main Menu");
        bntJudgeMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntJudgeMainMenuActionPerformed(evt);
            }
        });

        btnCivilianMainMenu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnCivilianMainMenu.setText("Civilian Main Menu");
        btnCivilianMainMenu.setToolTipText("Civilian Main Menu");
        btnCivilianMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCivilianMainMenuActionPerformed(evt);
            }
        });

        btnClerkMainMenu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnClerkMainMenu.setText("Clerk Main Menu");
        btnClerkMainMenu.setToolTipText("Clerk Main Menu");
        btnClerkMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClerkMainMenuActionPerformed(evt);
            }
        });

        btnLawyerMainMenu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnLawyerMainMenu.setText("Lawyer Main Menu");
        btnLawyerMainMenu.setToolTipText("Lawyer Main Menu");
        btnLawyerMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLawyerMainMenuActionPerformed(evt);
            }
        });

        mainMenuLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mainMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainMenuLabel.setText("Main Menu");
        mainMenuLabel.setToolTipText("Main Menu");

        javax.swing.GroupLayout ccmsMainMenuPanelLayout = new javax.swing.GroupLayout(ccmsMainMenuPanel);
        ccmsMainMenuPanel.setLayout(ccmsMainMenuPanelLayout);
        ccmsMainMenuPanelLayout.setHorizontalGroup(
            ccmsMainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ccmsMainMenuPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(ccmsMainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ccmsMainMenuPanelLayout.createSequentialGroup()
                        .addGroup(ccmsMainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ccmsMainMenuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                            .addComponent(mainMenuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(ccmsMainMenuPanelLayout.createSequentialGroup()
                        .addGroup(ccmsMainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ccmsMainMenuPanelLayout.createSequentialGroup()
                                .addGroup(ccmsMainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnLawyerMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bntJudgeMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnClerkMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCivilianMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(36, 36, 36)))
                        .addGap(0, 178, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ccmsMainMenuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnQuit)
                .addGap(120, 120, 120))
        );
        ccmsMainMenuPanelLayout.setVerticalGroup(
            ccmsMainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ccmsMainMenuPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ccmsMainMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(mainMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnCivilianMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnClerkMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(bntJudgeMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19)
                .addComponent(btnLawyerMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(53, 53, 53)
                .addComponent(btnQuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorMessageLabel)
                .addGap(149, 149, 149))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ccmsMainMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ccmsMainMenuPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntJudgeMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntJudgeMainMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntJudgeMainMenuActionPerformed

    private void btnCivilianMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCivilianMainMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCivilianMainMenuActionPerformed

    private void btnClerkMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClerkMainMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClerkMainMenuActionPerformed

    private void btnLawyerMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLawyerMainMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLawyerMainMenuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bntJudgeMainMenu;
    public javax.swing.JButton btnCivilianMainMenu;
    public javax.swing.JButton btnClerkMainMenu;
    public javax.swing.JButton btnLawyerMainMenu;
    public javax.swing.JButton btnQuit;
    private javax.swing.JLabel ccmsMainMenuLabel;
    private javax.swing.JPanel ccmsMainMenuPanel;
    private javax.swing.JLabel errorMessageLabel;
    private javax.swing.JLabel mainMenuLabel;
    // End of variables declaration//GEN-END:variables

}
