package ccms_mvc.view.Lawyer;

import ccms_mvc.controller.Lawyer.LawyerSearchCntl;
import ccms_mvc.model.CourtCases;
import java.util.List;

/**
 * This class sets up the is LawyerSearchUI Form.
 *
 * @author Tiffany Dove
 */
public class LawyerSearchUI extends javax.swing.JFrame {

    //Reference to LawyerSearchCntl Controller
    private LawyerSearchCntl lawyerSearchCntl;

    //Array List of Court Cases
    private List<CourtCases> listCourtCases;

    //Counter of the current Court Case
    private int indexOfCurrentCourtCase = 0;

    //Reference to CourtCases class
    private CourtCases courtCases;

    //Boolean variable to check if this is the first execution
    private boolean blnFirstTime = true;

    //Get the index of the current court case
    public int getIndexOfCurrentCourtCase() {
        return indexOfCurrentCourtCase;
    }

    //Set the index of the current court case
    public void setIndexOfCurrentCourtCase(int indexOfCurrentCourtCase) {
        this.indexOfCurrentCourtCase = indexOfCurrentCourtCase;
    }

    /**
     * Creates new form LawyerSearchUI
     */
    public LawyerSearchUI(LawyerSearchCntl lawyerSearchCntl) {
        this.lawyerSearchCntl = lawyerSearchCntl;
        initComponents();

        //Retrieve a list of all of the court cases
        listCourtCases = lawyerSearchCntl.getArrayListCourtCases();

        if (blnFirstTime) {
            clearTheFieldsInCourtCasesUI();
            blnFirstTime = false;
        } else {
            //Retreive a specific court case from the list of court cases.
            courtCases = listCourtCases.get(indexOfCurrentCourtCase);

            //Using the CourtCase class, take the values and populate
            //the UI.
            parseCourtCases(courtCases);
        }
    }

    /**
     * Parse the Court Cases
     */
    public void parseCourtCases(CourtCases courtCases) {
        //Set the Case Number field
        this.caseNumberTextField.setText(courtCases.getCaseNumber());

    }

    /**
     * Clear the Fields in the Court Case UI
     */
    public void clearTheFieldsInCourtCasesUI() {
        //Set the Case Number field
        this.caseNumberTextField.setText("");

    }

    //Get the Case Number field
    public String getCaseNumberTextField() {
        return caseNumberTextField.getText();
    }

    //Set the Case Number field
    public void setCaseNumberTextField(String caseNumberTextFieldString) {
        this.caseNumberTextField.setText(caseNumberTextFieldString);
    }

    /**
     * Enable the buttons in the UI
     */
    public void enableButtons(boolean enabled) {
        this.btnLawyerMainMenu.setEnabled(enabled);
        this.btnSearch.setEnabled(enabled);
        this.btnQuit.setEnabled(enabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lawyerSearchSpecificCasesPanel = new javax.swing.JPanel();
        ccmsLabel = new javax.swing.JLabel();
        caseNumberLabel = new javax.swing.JLabel();
        caseNumberTextField = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnLawyerMainMenu = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        lawyerSearchSpecificCasesLabel = new javax.swing.JLabel();
        errorMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lawyerSearchSpecificCasesPanel.setToolTipText("Person Panel");

        ccmsLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ccmsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ccmsLabel.setText("Court Case Managment System");
        ccmsLabel.setToolTipText("Court Case Managment System");

        caseNumberLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        caseNumberLabel.setText("Case Number:");
        caseNumberLabel.setToolTipText("Case Number:");

        caseNumberTextField.setToolTipText("Please Enter a Case Number (i.e. 11111)");
        caseNumberTextField.setName("caseNumberTextField"); // NOI18N

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setToolTipText("Search Judge for Specifiic Case");

        btnLawyerMainMenu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnLawyerMainMenu.setText("Lawyer Main Menu");
        btnLawyerMainMenu.setToolTipText("Return to Lawyer Main Menu");

        btnQuit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnQuit.setText("Quit");
        btnQuit.setToolTipText("exit the application");

        lawyerSearchSpecificCasesLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lawyerSearchSpecificCasesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lawyerSearchSpecificCasesLabel.setText("Lawyer - Search Specific Cases");
        lawyerSearchSpecificCasesLabel.setToolTipText("Lawyer - Search Specific Cases");

        errorMessage.setForeground(new java.awt.Color(255, 0, 0));
        errorMessage.setToolTipText("");

        javax.swing.GroupLayout lawyerSearchSpecificCasesPanelLayout = new javax.swing.GroupLayout(lawyerSearchSpecificCasesPanel);
        lawyerSearchSpecificCasesPanel.setLayout(lawyerSearchSpecificCasesPanelLayout);
        lawyerSearchSpecificCasesPanelLayout.setHorizontalGroup(
            lawyerSearchSpecificCasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lawyerSearchSpecificCasesPanelLayout.createSequentialGroup()
                .addGroup(lawyerSearchSpecificCasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(lawyerSearchSpecificCasesPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(lawyerSearchSpecificCasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ccmsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lawyerSearchSpecificCasesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, lawyerSearchSpecificCasesPanelLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(lawyerSearchSpecificCasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lawyerSearchSpecificCasesPanelLayout.createSequentialGroup()
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(btnLawyerMainMenu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnQuit))
                            .addGroup(lawyerSearchSpecificCasesPanelLayout.createSequentialGroup()
                                .addGroup(lawyerSearchSpecificCasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(lawyerSearchSpecificCasesPanelLayout.createSequentialGroup()
                                        .addComponent(caseNumberLabel)
                                        .addGap(54, 54, 54)
                                        .addComponent(caseNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(errorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 77, Short.MAX_VALUE)))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        lawyerSearchSpecificCasesPanelLayout.setVerticalGroup(
            lawyerSearchSpecificCasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lawyerSearchSpecificCasesPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ccmsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lawyerSearchSpecificCasesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(lawyerSearchSpecificCasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(caseNumberLabel)
                    .addComponent(caseNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(errorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addGroup(lawyerSearchSpecificCasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lawyerSearchSpecificCasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSearch)
                        .addComponent(btnLawyerMainMenu))
                    .addComponent(btnQuit, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lawyerSearchSpecificCasesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lawyerSearchSpecificCasesPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnLawyerMainMenu;
    public javax.swing.JButton btnQuit;
    public javax.swing.JButton btnSearch;
    private javax.swing.JLabel caseNumberLabel;
    private javax.swing.JTextField caseNumberTextField;
    private javax.swing.JLabel ccmsLabel;
    public javax.swing.JLabel errorMessage;
    private javax.swing.JLabel lawyerSearchSpecificCasesLabel;
    private javax.swing.JPanel lawyerSearchSpecificCasesPanel;
    // End of variables declaration//GEN-END:variables

}
