package ccms_mvc.view.Lawyer;

import ccms_mvc.controller.Lawyer.LawyerMainMenuCntl;

/**
 *
 * @author Tiffany Dove
 */
public class LawyerMainMenuUI extends javax.swing.JFrame {

    //Reference to Person Controller
    private LawyerMainMenuCntl lawyerMainMenuCntl;
//    //An arrayList of Person
//    private ArrayList<Person> arrayListPerson;  
//    //Counter of the current Person
//    private int indexOfCurrentPerson = 0;
//    //Reference to Person class
//    private Person person;

//    public int getIndexOfCurrentPerson() {
//        return indexOfCurrentPerson;
//    }
//
//    public void setIndexOfCurrentPerson(int indexOfCurrentPerson) {
//        this.indexOfCurrentPerson = indexOfCurrentPerson;
//    }
    /**
     * Creates new form PersonUI
     */
    public LawyerMainMenuUI(LawyerMainMenuCntl lawyerMainMenuCntl) {
        this.lawyerMainMenuCntl = lawyerMainMenuCntl;
        initComponents();
//        arrayListPerson = mainMenuCntl.getListOfCourtCases();
//        //Get a Person occurrence from the arrayList using the current position.
//        //namely current person.
//        person = arrayListPerson.get(indexOfCurrentPerson);
//        //Using the Person (person) class, take the values and populate
//        //the UI.
//        parsePerson(person);
    }

//    public void parsePerson(Person person) {
//        //set the UI's id num text field with the id num from Person
//        idNumTextField.setText(String.valueOf(person.getIdNum()));
//        //set the UI's name text field with the name from Person
//        nameTextField.setText(person.getName());
//        //set the UI's address text field with the address from Person
//        addressTextField.setText(person.getAddress());
//        //set the UI's city text field with the city from Person
//        cityTextField.setText(person.getCity());
//        //set the UI's state text field with the state from Person
//        stateTextField.setText(person.getState());
//        //set the UI's zip code text field with the zip code from Person
//        zipCodeTextField.setText(String.valueOf(person.getZipCode()));
//    }
//
//    public void clearTheFieldsInPersonUI() {
//        //set the UI's id num text field with the id num from Person
//        idNumTextField.setText("");
//        //set the UI's name text field with the name from Person
//        nameTextField.setText("");
//        //set the UI's address text field with the address from Person
//        addressTextField.setText("");
//        //set the UI's city text field with the city from Person
//        cityTextField.setText("");
//        //set the UI's state text field with the state from Person
//        stateTextField.setText("");
//        //set the UI's zip code text field with the zip code from Person
//        zipCodeTextField.setText("");
//    }
//
//    public String getAddressTextField() {
//        return addressTextField.getText();
//    }
//
//    public void setAddressTextField(String addressTextFieldString) {
//        this.addressTextField.setText(addressTextFieldString);
//    }
//
//    public String getCityTextField() {
//        return cityTextField.getText();
//    }
//
//    public void setCityTextField(String cityTextFieldString) {
//        this.cityTextField.setText(cityTextFieldString);
//    }
//
//    public String getIdNumTextField() {
//        return idNumTextField.getText();
//    }
//
//    public void setIdNumTextField(String idNumTextFieldString) {
//        this.idNumTextField.setText(idNumTextFieldString);
//    }
//
//    public String getNameTextField() {
//        return nameTextField.getText();
//    }
//
//    public void setNameTextField(String nameTextFieldString) {
//        this.nameTextField.setText(nameTextFieldString);
//    }
//
//    public String getStateTextField() {
//        return stateTextField.getText();
//    }
//
    public void setErrorMessageString(String errorMessageString) {
        this.errorMessageLabel.setText(errorMessageString);
    }

//    public String getZipCodeTextField() {
//        return zipCodeTextField.getText();
//    }
//
//    public void setZipCodeTextField(String zipCodeTextFieldString) {
//        this.zipCodeTextField.setText(zipCodeTextFieldString);
//    }
    public void enableButtons(boolean enabled) {

        this.btnLawyerSearchSpecificCase.setEnabled(enabled);
        this.btnLawyerViewCaseDetails.setEnabled(enabled);
        this.btnQuit.setEnabled(enabled);
        this.btnMainMenu.setEnabled(enabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lawyerMainMenuPanel = new javax.swing.JPanel();
        ccmsMainMenuLabel = new javax.swing.JLabel();
        btnQuit = new javax.swing.JButton();
        btnLawyerSearchSpecificCase = new javax.swing.JButton();
        btnLawyerViewCaseDetails = new javax.swing.JButton();
        errorMessageLabel = new javax.swing.JLabel();
        btnMainMenu = new javax.swing.JButton();
        lawyerMainMenuLabel = new javax.swing.JLabel();
        btnDetailedInformation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lawyerMainMenuPanel.setToolTipText("Lawyer Main Menu Panel");

        ccmsMainMenuLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ccmsMainMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ccmsMainMenuLabel.setText("Court Case Management System");
        ccmsMainMenuLabel.setToolTipText("Court Case Management System");

        btnQuit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnQuit.setText("Quit");
        btnQuit.setToolTipText("exit the application");

        btnLawyerSearchSpecificCase.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnLawyerSearchSpecificCase.setText("Search Specific Case");
        btnLawyerSearchSpecificCase.setToolTipText("Search Specific Case");
        btnLawyerSearchSpecificCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLawyerSearchSpecificCaseActionPerformed(evt);
            }
        });

        btnLawyerViewCaseDetails.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnLawyerViewCaseDetails.setText("View Case Details");
        btnLawyerViewCaseDetails.setToolTipText("View Case Details");
        btnLawyerViewCaseDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLawyerViewCaseDetailsActionPerformed(evt);
            }
        });

        btnMainMenu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnMainMenu.setText("Main Menu");
        btnMainMenu.setToolTipText("exit the application");

        lawyerMainMenuLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lawyerMainMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lawyerMainMenuLabel.setText("Lawyer Main Menu");
        lawyerMainMenuLabel.setToolTipText("Lawyer Main Menu");

        btnDetailedInformation.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDetailedInformation.setText("Detailed Information");
        btnDetailedInformation.setToolTipText("View Case Details for Lawyer");

        javax.swing.GroupLayout lawyerMainMenuPanelLayout = new javax.swing.GroupLayout(lawyerMainMenuPanel);
        lawyerMainMenuPanel.setLayout(lawyerMainMenuPanelLayout);
        lawyerMainMenuPanelLayout.setHorizontalGroup(
            lawyerMainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lawyerMainMenuPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(lawyerMainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lawyerMainMenuPanelLayout.createSequentialGroup()
                        .addGroup(lawyerMainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ccmsMainMenuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                            .addComponent(lawyerMainMenuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(lawyerMainMenuPanelLayout.createSequentialGroup()
                        .addGroup(lawyerMainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDetailedInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLawyerSearchSpecificCase)
                            .addComponent(btnLawyerViewCaseDetails)
                            .addComponent(errorMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(lawyerMainMenuPanelLayout.createSequentialGroup()
                                .addComponent(btnQuit)
                                .addGap(123, 123, 123)
                                .addComponent(btnMainMenu)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        lawyerMainMenuPanelLayout.setVerticalGroup(
            lawyerMainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lawyerMainMenuPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ccmsMainMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lawyerMainMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnLawyerSearchSpecificCase)
                .addGap(28, 28, 28)
                .addComponent(btnLawyerViewCaseDetails)
                .addGap(29, 29, 29)
                .addComponent(btnDetailedInformation)
                .addGap(61, 61, 61)
                .addComponent(errorMessageLabel)
                .addGap(69, 69, 69)
                .addGroup(lawyerMainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMainMenu)
                    .addComponent(btnQuit))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lawyerMainMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lawyerMainMenuPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLawyerSearchSpecificCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLawyerSearchSpecificCaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLawyerSearchSpecificCaseActionPerformed

    private void btnLawyerViewCaseDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLawyerViewCaseDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLawyerViewCaseDetailsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDetailedInformation;
    public javax.swing.JButton btnLawyerSearchSpecificCase;
    public javax.swing.JButton btnLawyerViewCaseDetails;
    public javax.swing.JButton btnMainMenu;
    public javax.swing.JButton btnQuit;
    private javax.swing.JLabel ccmsMainMenuLabel;
    private javax.swing.JLabel errorMessageLabel;
    private javax.swing.JLabel lawyerMainMenuLabel;
    private javax.swing.JPanel lawyerMainMenuPanel;
    // End of variables declaration//GEN-END:variables

}
