package ccms_mvc.view.Lawyer;

import ccms_mvc.controller.Lawyer.LawyerMainMenuCntl;

/**
 * This class sets up the is LawyerMainMenuUI Form.
 *
 * @author Tiffany Dove
 */
public class LawyerMainMenuUI extends javax.swing.JFrame {

    //Reference to LawyerMainMenuCntl Controller
    private LawyerMainMenuCntl lawyerMainMenuCntl;

    /**
     * Creates new form LawyerMainMenuUI
     */
    public LawyerMainMenuUI(LawyerMainMenuCntl lawyerMainMenuCntl) {
        this.lawyerMainMenuCntl = lawyerMainMenuCntl;
        initComponents();
    }

    //Set Error Message Field
    public void setErrorMessageString(String errorMessageString) {
        this.errorMessageLabel.setText(errorMessageString);
    }

    /**
     * Enable the buttons in the UI
     */
    public void enableButtons(boolean enabled) {
        this.btnLawyerSearchSpecificCase.setEnabled(enabled);
        this.btnLawyerViewCaseDetails.setEnabled(enabled);
        this.btnQuit.setEnabled(enabled);
        this.btnMainMenu.setEnabled(enabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lawyerMainMenuPanel = new javax.swing.JPanel();
        ccmsMainMenuLabel = new javax.swing.JLabel();
        btnQuit = new javax.swing.JButton();
        btnLawyerSearchSpecificCase = new javax.swing.JButton();
        btnLawyerViewCaseDetails = new javax.swing.JButton();
        errorMessageLabel = new javax.swing.JLabel();
        btnMainMenu = new javax.swing.JButton();
        lawyerMainMenuLabel = new javax.swing.JLabel();
        btnDetailedInformation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lawyerMainMenuPanel.setToolTipText("Lawyer Main Menu Panel");

        ccmsMainMenuLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ccmsMainMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ccmsMainMenuLabel.setText("Court Case Management System");
        ccmsMainMenuLabel.setToolTipText("Court Case Management System");

        btnQuit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnQuit.setText("Quit");
        btnQuit.setToolTipText("exit the application");

        btnLawyerSearchSpecificCase.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnLawyerSearchSpecificCase.setText("Search Specific Case");
        btnLawyerSearchSpecificCase.setToolTipText("Search Specific Case");
        btnLawyerSearchSpecificCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLawyerSearchSpecificCaseActionPerformed(evt);
            }
        });

        btnLawyerViewCaseDetails.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnLawyerViewCaseDetails.setText("View Case Details");
        btnLawyerViewCaseDetails.setToolTipText("View Case Details");
        btnLawyerViewCaseDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLawyerViewCaseDetailsActionPerformed(evt);
            }
        });

        btnMainMenu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnMainMenu.setText("Main Menu");
        btnMainMenu.setToolTipText("exit the application");

        lawyerMainMenuLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lawyerMainMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lawyerMainMenuLabel.setText("Lawyer Main Menu");
        lawyerMainMenuLabel.setToolTipText("Lawyer Main Menu");

        btnDetailedInformation.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDetailedInformation.setText("Detailed Information");
        btnDetailedInformation.setToolTipText("View Case Details for Lawyer");

        javax.swing.GroupLayout lawyerMainMenuPanelLayout = new javax.swing.GroupLayout(lawyerMainMenuPanel);
        lawyerMainMenuPanel.setLayout(lawyerMainMenuPanelLayout);
        lawyerMainMenuPanelLayout.setHorizontalGroup(
            lawyerMainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lawyerMainMenuPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(lawyerMainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lawyerMainMenuPanelLayout.createSequentialGroup()
                        .addGroup(lawyerMainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ccmsMainMenuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                            .addComponent(lawyerMainMenuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(lawyerMainMenuPanelLayout.createSequentialGroup()
                        .addGroup(lawyerMainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDetailedInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLawyerSearchSpecificCase)
                            .addComponent(btnLawyerViewCaseDetails)
                            .addComponent(errorMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(lawyerMainMenuPanelLayout.createSequentialGroup()
                                .addComponent(btnQuit)
                                .addGap(123, 123, 123)
                                .addComponent(btnMainMenu)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        lawyerMainMenuPanelLayout.setVerticalGroup(
            lawyerMainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lawyerMainMenuPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ccmsMainMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lawyerMainMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnLawyerSearchSpecificCase)
                .addGap(28, 28, 28)
                .addComponent(btnLawyerViewCaseDetails)
                .addGap(29, 29, 29)
                .addComponent(btnDetailedInformation)
                .addGap(61, 61, 61)
                .addComponent(errorMessageLabel)
                .addGap(69, 69, 69)
                .addGroup(lawyerMainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMainMenu)
                    .addComponent(btnQuit))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lawyerMainMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lawyerMainMenuPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLawyerSearchSpecificCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLawyerSearchSpecificCaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLawyerSearchSpecificCaseActionPerformed

    private void btnLawyerViewCaseDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLawyerViewCaseDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLawyerViewCaseDetailsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDetailedInformation;
    public javax.swing.JButton btnLawyerSearchSpecificCase;
    public javax.swing.JButton btnLawyerViewCaseDetails;
    public javax.swing.JButton btnMainMenu;
    public javax.swing.JButton btnQuit;
    private javax.swing.JLabel ccmsMainMenuLabel;
    private javax.swing.JLabel errorMessageLabel;
    private javax.swing.JLabel lawyerMainMenuLabel;
    private javax.swing.JPanel lawyerMainMenuPanel;
    // End of variables declaration//GEN-END:variables

}
