package ccms_mvc.view.Clerk;

import ccms_mvc.controller.Clerk.ClerkMainMenuCntl;

/**
 * This class sets up the is ClerkMainMenuUI Form.
 *
 * @author Tiffany Dove
 */
public class ClerkMainMenuUI extends javax.swing.JFrame {

    //Reference to ClerkMainMenuCntl Controller
    private ClerkMainMenuCntl clerkMainMenuCntl;

    /**
     * Creates new form ClerkMainMenuUI
     */
    public ClerkMainMenuUI(ClerkMainMenuCntl clerkMainMenuCntl) {
        this.clerkMainMenuCntl = clerkMainMenuCntl;
        initComponents();

    }

    public void setErrorMessageString(String errorMessageString) {
        this.errorMessageLabel.setText(errorMessageString);
    }

    /**
     * Enable the buttons in the UI
     */
    public void enableButtons(boolean enabled) {

        this.btnSearchSpecificCase.setEnabled(enabled);
        this.btnViewCaseDetails.setEnabled(enabled);
        this.btnQuit.setEnabled(enabled);
        this.btnMainMenu.setEnabled(enabled);
        this.btnDetailedInformation.setEnabled(enabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clerkMainMenuPanel = new javax.swing.JPanel();
        ccmsMainMenuLabel = new javax.swing.JLabel();
        btnQuit = new javax.swing.JButton();
        btnSearchSpecificCase = new javax.swing.JButton();
        btnViewCaseDetails = new javax.swing.JButton();
        errorMessageLabel = new javax.swing.JLabel();
        btnMainMenu = new javax.swing.JButton();
        clerkMainMenuLabel = new javax.swing.JLabel();
        btnDetailedInformation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clerkMainMenuPanel.setToolTipText("Clerk Main Menu Panel");

        ccmsMainMenuLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ccmsMainMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ccmsMainMenuLabel.setText("Court Case Management System");
        ccmsMainMenuLabel.setToolTipText("Court Case Management System");

        btnQuit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnQuit.setText("Quit");
        btnQuit.setToolTipText("exit the application");

        btnSearchSpecificCase.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSearchSpecificCase.setText("Search Specific Case");
        btnSearchSpecificCase.setToolTipText("Search Specific Case for Clerk");

        btnViewCaseDetails.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnViewCaseDetails.setText("View Case Details");
        btnViewCaseDetails.setToolTipText("View Case Details for Clerk");

        btnMainMenu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnMainMenu.setText("Main Menu");
        btnMainMenu.setToolTipText("exit the application");

        clerkMainMenuLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clerkMainMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clerkMainMenuLabel.setText("Clerk Main Menu");
        clerkMainMenuLabel.setToolTipText("Clerk Main Menu");

        btnDetailedInformation.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDetailedInformation.setText("Detailed Information");
        btnDetailedInformation.setToolTipText("View Case Details for Clerk");

        javax.swing.GroupLayout clerkMainMenuPanelLayout = new javax.swing.GroupLayout(clerkMainMenuPanel);
        clerkMainMenuPanel.setLayout(clerkMainMenuPanelLayout);
        clerkMainMenuPanelLayout.setHorizontalGroup(
            clerkMainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clerkMainMenuPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(clerkMainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clerkMainMenuPanelLayout.createSequentialGroup()
                        .addGroup(clerkMainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(clerkMainMenuPanelLayout.createSequentialGroup()
                                .addComponent(btnQuit)
                                .addGap(123, 123, 123)
                                .addComponent(btnMainMenu))
                            .addGroup(clerkMainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnSearchSpecificCase, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                .addComponent(btnViewCaseDetails, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDetailedInformation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(clerkMainMenuPanelLayout.createSequentialGroup()
                        .addGroup(clerkMainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ccmsMainMenuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                            .addComponent(clerkMainMenuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        clerkMainMenuPanelLayout.setVerticalGroup(
            clerkMainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clerkMainMenuPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ccmsMainMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(clerkMainMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnSearchSpecificCase)
                .addGap(22, 22, 22)
                .addComponent(btnViewCaseDetails)
                .addGap(19, 19, 19)
                .addComponent(btnDetailedInformation)
                .addGap(113, 113, 113)
                .addComponent(errorMessageLabel)
                .addGap(69, 69, 69)
                .addGroup(clerkMainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMainMenu)
                    .addComponent(btnQuit))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(clerkMainMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clerkMainMenuPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDetailedInformation;
    public javax.swing.JButton btnMainMenu;
    public javax.swing.JButton btnQuit;
    public javax.swing.JButton btnSearchSpecificCase;
    public javax.swing.JButton btnViewCaseDetails;
    private javax.swing.JLabel ccmsMainMenuLabel;
    private javax.swing.JLabel clerkMainMenuLabel;
    private javax.swing.JPanel clerkMainMenuPanel;
    private javax.swing.JLabel errorMessageLabel;
    // End of variables declaration//GEN-END:variables

}
