package ccms_mvc.view.Clerk;

import ccms_mvc.controller.Clerk.ClerkMainMenuCntl;

/**
 *
 * @author Tiffany Dove
 */
public class ClerkMainMenuUI extends javax.swing.JFrame {

    //Reference to Person Controller
    private ClerkMainMenuCntl clerkMainMenuCntl;
//    //An arrayList of Person
//    private ArrayList<Person> arrayListPerson;  
//    //Counter of the current Person
//    private int indexOfCurrentPerson = 0;
//    //Reference to Person class
//    private Person person;

//    public int getIndexOfCurrentPerson() {
//        return indexOfCurrentPerson;
//    }
//
//    public void setIndexOfCurrentPerson(int indexOfCurrentPerson) {
//        this.indexOfCurrentPerson = indexOfCurrentPerson;
//    }
            
    /**
     * Creates new form PersonUI
     */
    public ClerkMainMenuUI(ClerkMainMenuCntl clerkMainMenuCntl) {
        this.clerkMainMenuCntl = clerkMainMenuCntl;
        initComponents();
//        arrayListPerson = mainMenuCntl.getListOfCourtCases();
//        //Get a Person occurrence from the arrayList using the current position.
//        //namely current person.
//        person = arrayListPerson.get(indexOfCurrentPerson);
//        //Using the Person (person) class, take the values and populate
//        //the UI.
//        parsePerson(person);
    }

//    public void parsePerson(Person person) {
//        //set the UI's id num text field with the id num from Person
//        idNumTextField.setText(String.valueOf(person.getIdNum()));
//        //set the UI's name text field with the name from Person
//        nameTextField.setText(person.getName());
//        //set the UI's address text field with the address from Person
//        addressTextField.setText(person.getAddress());
//        //set the UI's city text field with the city from Person
//        cityTextField.setText(person.getCity());
//        //set the UI's state text field with the state from Person
//        stateTextField.setText(person.getState());
//        //set the UI's zip code text field with the zip code from Person
//        zipCodeTextField.setText(String.valueOf(person.getZipCode()));
//    }
//
//    public void clearTheFieldsInPersonUI() {
//        //set the UI's id num text field with the id num from Person
//        idNumTextField.setText("");
//        //set the UI's name text field with the name from Person
//        nameTextField.setText("");
//        //set the UI's address text field with the address from Person
//        addressTextField.setText("");
//        //set the UI's city text field with the city from Person
//        cityTextField.setText("");
//        //set the UI's state text field with the state from Person
//        stateTextField.setText("");
//        //set the UI's zip code text field with the zip code from Person
//        zipCodeTextField.setText("");
//    }
//
//    public String getAddressTextField() {
//        return addressTextField.getText();
//    }
//
//    public void setAddressTextField(String addressTextFieldString) {
//        this.addressTextField.setText(addressTextFieldString);
//    }
//
//    public String getCityTextField() {
//        return cityTextField.getText();
//    }
//
//    public void setCityTextField(String cityTextFieldString) {
//        this.cityTextField.setText(cityTextFieldString);
//    }
//
//    public String getIdNumTextField() {
//        return idNumTextField.getText();
//    }
//
//    public void setIdNumTextField(String idNumTextFieldString) {
//        this.idNumTextField.setText(idNumTextFieldString);
//    }
//
//    public String getNameTextField() {
//        return nameTextField.getText();
//    }
//
//    public void setNameTextField(String nameTextFieldString) {
//        this.nameTextField.setText(nameTextFieldString);
//    }
//
//    public String getStateTextField() {
//        return stateTextField.getText();
//    }
//
    public void setErrorMessageString(String errorMessageString) {
        this.errorMessageLabel.setText(errorMessageString);
    }

//    public String getZipCodeTextField() {
//        return zipCodeTextField.getText();
//    }
//
//    public void setZipCodeTextField(String zipCodeTextFieldString) {
//        this.zipCodeTextField.setText(zipCodeTextFieldString);
//    }
    
    public void enableButtons(boolean enabled){
        
        this.btnSearchSpecificCase.setEnabled(enabled);
        this.btnViewCaseDetails.setEnabled(enabled);
        this.btnQuit.setEnabled(enabled);
        this.btnMainMenu.setEnabled(enabled);
        this.btnDetailedInformation.setEnabled(enabled);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clerkMainMenuPanel = new javax.swing.JPanel();
        ccmsMainMenuLabel = new javax.swing.JLabel();
        btnQuit = new javax.swing.JButton();
        btnSearchSpecificCase = new javax.swing.JButton();
        btnViewCaseDetails = new javax.swing.JButton();
        errorMessageLabel = new javax.swing.JLabel();
        btnMainMenu = new javax.swing.JButton();
        clerkMainMenuLabel = new javax.swing.JLabel();
        btnDetailedInformation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clerkMainMenuPanel.setToolTipText("Person Panel");

        ccmsMainMenuLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ccmsMainMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ccmsMainMenuLabel.setText("Court Case Management System");
        ccmsMainMenuLabel.setToolTipText("Court Case Management System");

        btnQuit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnQuit.setText("Quit");
        btnQuit.setToolTipText("exit the application");

        btnSearchSpecificCase.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSearchSpecificCase.setText("Search Specific Case");
        btnSearchSpecificCase.setToolTipText("Search Specific Case for Clerk");

        btnViewCaseDetails.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnViewCaseDetails.setText("View Case Details");
        btnViewCaseDetails.setToolTipText("View Case Details for Clerk");

        btnMainMenu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnMainMenu.setText("Main Menu");
        btnMainMenu.setToolTipText("exit the application");

        clerkMainMenuLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clerkMainMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clerkMainMenuLabel.setText("Clerk Main Menu");
        clerkMainMenuLabel.setToolTipText("Clerk Main Menu");

        btnDetailedInformation.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDetailedInformation.setText("Detailed Information");
        btnDetailedInformation.setToolTipText("View Case Details for Clerk");

        javax.swing.GroupLayout clerkMainMenuPanelLayout = new javax.swing.GroupLayout(clerkMainMenuPanel);
        clerkMainMenuPanel.setLayout(clerkMainMenuPanelLayout);
        clerkMainMenuPanelLayout.setHorizontalGroup(
            clerkMainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clerkMainMenuPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(clerkMainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clerkMainMenuPanelLayout.createSequentialGroup()
                        .addGroup(clerkMainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(clerkMainMenuPanelLayout.createSequentialGroup()
                                .addComponent(btnQuit)
                                .addGap(123, 123, 123)
                                .addComponent(btnMainMenu))
                            .addGroup(clerkMainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnSearchSpecificCase, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                .addComponent(btnViewCaseDetails, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDetailedInformation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(clerkMainMenuPanelLayout.createSequentialGroup()
                        .addGroup(clerkMainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ccmsMainMenuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                            .addComponent(clerkMainMenuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        clerkMainMenuPanelLayout.setVerticalGroup(
            clerkMainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clerkMainMenuPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ccmsMainMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(clerkMainMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnSearchSpecificCase)
                .addGap(22, 22, 22)
                .addComponent(btnViewCaseDetails)
                .addGap(19, 19, 19)
                .addComponent(btnDetailedInformation)
                .addGap(113, 113, 113)
                .addComponent(errorMessageLabel)
                .addGap(69, 69, 69)
                .addGroup(clerkMainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMainMenu)
                    .addComponent(btnQuit))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(clerkMainMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clerkMainMenuPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDetailedInformation;
    public javax.swing.JButton btnMainMenu;
    public javax.swing.JButton btnQuit;
    public javax.swing.JButton btnSearchSpecificCase;
    public javax.swing.JButton btnViewCaseDetails;
    private javax.swing.JLabel ccmsMainMenuLabel;
    private javax.swing.JLabel clerkMainMenuLabel;
    private javax.swing.JPanel clerkMainMenuPanel;
    private javax.swing.JLabel errorMessageLabel;
    // End of variables declaration//GEN-END:variables

}
